#include <glwrapper/Framebuffer.h>

#define ENUM_TO_STRING_CASE(EN) case EN: message = #EN; break
namespace GLWrapper 
{



	std::string Framebuffer::GetErrorMessage()
	{
		std::string message;
		switch (CheckStatus())
		{
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_COMPLETE);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_UNDEFINED);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_UNSUPPORTED);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE);
			ENUM_TO_STRING_CASE(GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS);
		default:
			message = "Unknown error";
		break;
		}
		return message;
	}

}